# Generated by Django 5.1.6 on 2025-03-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('pw', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('desc', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('prof', models.ManyToManyField(to='rate.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.module')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.professor')),
            ],
        ),
    ]
