# Generated by Django 5.1.6 on 2025-03-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField(choices=[(1, '1'), (2, '2')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='module',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module_instance',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.module'),
        ),
        migrations.AddField(
            model_name='module_instance',
            name='prof',
            field=models.ManyToManyField(to='rate.professor'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.module_instance'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'professor', 'module')},
        ),
    ]
