# Generated by Django 5.1.6 on 2025-03-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_module_instance_delete_user_remove_module_prof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
