# Generated by Django 5.1.6 on 2025-03-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_alter_professor_id_alter_professor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_instance',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.module'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.professor'),
        ),
    ]
