# Generated by Django 5.1.6 on 2025-03-10 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_alter_module_instance_mod_alter_rating_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module_instance',
            old_name='mod',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='module_instance',
            old_name='prof',
            new_name='professor',
        ),
        migrations.AlterField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.professor'),
        ),
    ]
