# Generated by Django 5.1.6 on 2025-03-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_rename_mod_module_instance_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
