# Generated by Django 5.1.6 on 2025-03-10 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.professor'),
        ),
    ]
