# Generated by Django 5.1.6 on 2025-03-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_alter_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='stars',
            new_name='rating',
        ),
    ]
